name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        BUILD_TARGET: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        rustup target add ${{ matrix.BUILD_TARGET }}
    - name: Build
      run: cargo build --release --target ${{ matrix.BUILD_TARGET }}
    - name: Get version
      id: version
      run: |
        echo "version=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload release artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/${{ matrix.BUILD_TARGET }}/release/vrc-owo${{ matrix.BUILD_TARGET == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
        asset_name: vrc-owo${{ matrix.BUILD_TARGET == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
        asset_content_type: application/octet-stream

